class RandomGenerator{
	constructor(min, max){ 
		
		//takes in the minimum and maximum values - check
		//if they are not defined, it sets the minimum to 1, and the max to 10
		//makes storage for the random number
		this.min = min; //#endregion
		this.max = max;
		this.storeRandomNumber = null;
		
	};
	generate(){
		//make a random value between the minimum and maximum values
		//and store the number into the storage from the constructor

		this.storeRandomNumber = Math.floor(Math.random()*(this.max-this.min+1)+this.min);	
	};
	getRange(){
		//return an object with min and max, min being the minimum value for the generator, max being the maximum value
		//returns a basic object literal
		var returnMinMax = {
			min: this.min,
			max: this.max
		};
		return returnMinMax;
	};
	getNum(){
		//return the random number that was generated by generate()
		return this.storeRandomNumber;
	};
};